from fastapi import FastAPI, HTTPException, Query
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, PlainTextResponse
from fastapi.middleware.cors import CORSMiddleware
import httpx
from datetime import datetime
import os

app = FastAPI(title="Weather App")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

API_KEY = "87d845b0b6cf29baa1a73cc34b067a95"
BASE_URL = "https://api.openweathermap.org/data/2.5"

app.mount("/static", StaticFiles(directory="static"), name="static")


@app.get("/")
async def root():
    return FileResponse("static/index.html")


@app.get("/api/weather")
async def get_weather(city: str = Query(..., description="City name")):
    async with httpx.AsyncClient() as client:
        # Current weather
        current_res = await client.get(
            f"{BASE_URL}/weather",
            params={"q": city, "appid": API_KEY, "units": "metric"}
        )
        if current_res.status_code == 404:
            raise HTTPException(status_code=404, detail="City not found")
        if current_res.status_code != 200:
            raise HTTPException(status_code=500, detail="Weather API error")

        current = current_res.json()

        # 5-day forecast
        forecast_res = await client.get(
            f"{BASE_URL}/forecast",
            params={"q": city, "appid": API_KEY, "units": "metric"}
        )
        forecast_data = forecast_res.json()

    # Process forecast - one entry per day (noon slot)
    daily = {}
    for item in forecast_data["list"]:
        date = item["dt_txt"].split(" ")[0]
        time = item["dt_txt"].split(" ")[1]
        if time == "12:00:00" and len(daily) < 5:
            daily[date] = {
                "date": datetime.strptime(date, "%Y-%m-%d").strftime("%a, %d %b"),
                "temp_max": round(item["main"]["temp_max"]),
                "temp_min": round(item["main"]["temp_min"]),
                "description": item["weather"][0]["description"].title(),
                "icon": item["weather"][0]["icon"],
                "humidity": item["main"]["humidity"],
                "wind_speed": item["wind"]["speed"],
            }

    return {
        "city": current["name"],
        "country": current["sys"]["country"],
        "current": {
            "temp": round(current["main"]["temp"]),
            "feels_like": round(current["main"]["feels_like"]),
            "description": current["weather"][0]["description"].title(),
            "icon": current["weather"][0]["icon"],
            "humidity": current["main"]["humidity"],
            "wind_speed": current["wind"]["speed"],
            "pressure": current["main"]["pressure"],
            "visibility": current.get("visibility", 0) // 1000,
        },
        "forecast": list(daily.values()),
    }


@app.get("/api/download")
async def download_weather(city: str = Query(...)):
    async with httpx.AsyncClient() as client:
        res = await client.get(
            f"{BASE_URL}/weather",
            params={"q": city, "appid": API_KEY, "units": "metric"}
        )
        if res.status_code != 200:
            raise HTTPException(status_code=404, detail="City not found")
        data = res.json()

    date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")
    temp = round(data["main"]["temp"], 2)
    desc = data["weather"][0]["description"].title()
    humidity = data["main"]["humidity"]
    wind = data["wind"]["speed"]

    content = f"""==============================================================
    WEATHER STATS FOR - {city.upper()} || {date_time}
    ==============================================================
    Current Temperature : {temp} °C
    Feels Like          : {round(data['main']['feels_like'], 2)} °C
    Weather Description : {desc}
    Humidity            : {humidity} %
    Wind Speed          : {wind_kmh} km/h
    Pressure            : {data['main']['pressure']} hPa
    ==============================================================
    Generated by WeatherApp
    =============================================================="""
    
    return PlainTextResponse(
        content=content,
        headers={"Content-Disposition": f"attachment; filename=weather_{city}.txt"}
    )
